### ISSUE TITLE
[BUG] 无法禁用重命名节点

### ISSUE THREAD

**Issue by gaoyuyun** [beck-8/subs-check#116]
### 前置确认

- [x] 我已阅读 [README.md](https://github.com/beck-8/subs-check/blob/master/README.md)，确认问题不是配置错误。
- [x] 我已在 [Issues](https://github.com/beck-8/subs-check/issues) 中搜索，未找到类似的问题。
- [x] 我已在 [config.example.yaml](https://github.com/beck-8/subs-check/blob/master/config/config.example.yaml) 中看过，未找到相关配置

### 问题描述

希望不使用自带的节点重命名功能，设置config.yaml中的rename-node: false后仍然无法关闭

### 复现步骤

本地通过Docker先配置一个subs-check，可以正常运行，将节点重命名为flag+region+speed+service的格式，再通过Docker配置一个subs-check-2，里面的订阅链接使用第一个subs-check的，即http://{host-ip:8199}/sub/all.yaml，关闭测速和节点rename

### 预期行为

输出保留第一个subs-check重命名后的格式，不要重新命名
```
proxies:
    - alpn:
        - h2
        - http/1.1
      name: "\U0001F1ED\U0001F1F0香港1 | ⬇️ 3.5MB/s|0%|Youtube|Openai"
      skip-cert-verify: true
      type: trojan
    - alpn:
        - h2
        - http/1.1
      name: "\U0001F1ED\U0001F1F0香港2 | ⬇️ 3.5MB/s|0%|Youtube|Openai"
      skip-cert-verify: true
      type: trojan
    - alpn:
        - h2
        - http/1.1
      name: "\U0001F1ED\U0001F1F0香港3 | ⬇️ 3.5MB/s|0%|Youtube|Openai"
      skip-cert-verify: true
      type: trojan
    - alpn:
        - h3
      delay: 941
      down: 55
      name: "\U0001F1EB\U0001F1F7法国1 | ⬇️ 5.5MB/s|0%|Openai"
      protocol: udp
      skip-cert-verify: true
      sni: apple.com
      type: hysteria
      udp: true
      up: 11
```

### 实际行为

实际输出仍然重新命名了
```
proxies:
    - cipher: aes-256-gcm
      name: "\U0001F1F9\U0001F1FC台湾3"
      type: ss
    - cipher: aes-256-gcm
      name: "\U0001F1F9\U0001F1FC台湾2"
      type: ss
    - alpn:
        - h2
        - http/1.1
      name: "\U0001F1ED\U0001F1F0香港2"
      skip-cert-verify: true
      type: trojan
    - alpn:
        - h2
        - http/1.1
      name: "\U0001F1EF\U0001F1F5日本2"
      skip-cert-verify: true
      type: trojan
```

### subs-check 版本

v2.2.4

### 环境详情

Docker version 28.1.0

### 日志或截图

无
