### ISSUE TITLE
测试后的YAML节点识别不到

### ISSUE THREAD

**Issue by OP404OP** [beck-8/subs-check#15]
![Image](https://github.com/user-attachments/assets/2eb0e7ce-243b-4efb-ada2-8ccfc186e7b4)

![Image](https://github.com/user-attachments/assets/8d926575-2a64-46e0-ab8d-b3b12b2b1bff)

>我没有使用base.yaml模板，不太习惯使用内嵌https订阅地址方式。

下面是测试后生成的 **all.yaml**

```
proxies:
    - alterId: 0
      cipher: auto
      name: "\U0001F1F8\U0001F1EC新加坡1 | ⬇️ 12.6MB/s"
      network: tcp
      port: 3683
      server: 40daaab1-stl340-t238t8-6wpo.b.fosant.com
      tls: false
      type: vmess
      uuid: aada003a-bc20-11ee-8ebe-f23c93136cb3
    - alterId: 0
      cipher: auto
      name: "\U0001F1EB\U0001F1F7法国1 | ⬇️ 4.8MB/s"
      network: tcp
      port: 3686
      server: 902b2263-stl340-sxk0uf-4fy2.a.fosant.com
      tls: false
      type: vmess
      uuid: 753cc4e8-f9a3-11ed-bce0-f23c93665044
    - client-fingerprint: random
      flow: ""
      mode: ""
      name: "\U0001F1E9\U0001F1EA德国1 | ⬇️ 7.9MB/s"
      network: ws
      port: 2087
      server: pages.cloudflare.com
      servername: notls.019960.xyz
      tls: true
      type: vless
      udp: false
      uuid: 6340484d-c035-4a80-b703-e80adcae33a6
      ws-opts:
        headers:
            Host: notls.019960.xyz
        path: /
    - alterId: 2
      cipher: auto
      name: "\U0001F1ED\U0001F1F0香港1 | ⬇️ 9.1MB/s"
      network: ws
      port: 450
      server: 9336a7ff-stl340-sus9gj-d6ar.hkt.east.wctype.com
      tls: false
      type: vmess
      uuid: a16d62f6-048d-11f0-af5a-f23c93136cb3
      ws-headers:
        Host: webrtcpunch.video.qq.com
      ws-path: /
    - alterId: 0
      cipher: auto
      name: "\U0001F1EB\U0001F1F7法国2 | ⬇️ 4.6MB/s"
      network: tcp
      port: 3686
      server: 6db07985-stl340-su2qjz-3sq2.a.fosant.com
      tls: false
      type: vmess
      uuid: d6c7924e-8e0c-11ee-8657-f23c93141fad
    - alterId: 0
      cipher: auto
      name: "\U0001F1EB\U0001F1F7法国3 | ⬇️ 4.7MB/s"
      network: tcp
      port: 3686
      server: 1c7cdaa4-stl340-t9dorx-bu8s.a.fosant.com
      tls: false
      type: vmess
      uuid: cc1e8ba3-bcdc-11ef-b815-f23c9313b177
    - client-fingerprint: ""
      flow: ""
      mode: ""
      name: "\U0001F1F8\U0001F1EC新加坡2 | ⬇️ 9.2MB/s"
      network: ws
      port: 80
      server: 170.114.45.6
      servername: ""
      tls: false
      type: vless
      udp: false
      uuid: e7466ee9-073c-477a-8fab-e9b3792b7990
      ws-opts:
        headers:
            Host: group.darkshadoww.shop
        path: /
    - name: "\U0001F300其他1-VN | ⬇️ 2.0MB/s"
      password: de8eee7e-5a88-4001-9c46-b42f9e9fd682
      port: 53003
      server: in1.xiguajiasu.xyz
      skip-cert-verify: true
      sni: vn003.yijiasu.xyz
      type: trojan
      udp: true
    - alterId: 2
      cipher: auto
      name: "\U0001F1FA\U0001F1F8美国1 | ⬇️ 8.2MB/s"
      network: ws
      port: 420
      server: 5bc28db3-stl340-sxk0uf-4fy2.fmt2-us.sghuawei.com
      tls: false
      type: vmess
      uuid: 753cc4e8-f9a3-11ed-bce0-f23c93665044
      ws-headers:
        Host: webrtcpunch.video.qq.com
      ws-path: /
    - alterId: 2
      cipher: auto
      name: "\U0001F1ED\U0001F1F0香港2 | ⬇️ 2.9MB/s"
      network: ws
      port: 450
      server: 469e4415-stl340-stt2u4-63bp.hkt.east.wctype.com
      tls: false
      type: vmess
      uuid: 92b2a3d4-f353-11ef-b714-f23c93136cb3
      ws-headers:
        Host: webrtcpunch.video.qq.com
      ws-path: /
    - name: "\U0001F1EC\U0001F1E7英国1 | ⬇️ 3.6MB/s"
      password: mFhweJky
      port: 62903
      server: 154.209.135.56
      type: socks5
      username: eBVA1ULi
```

下面是我复制到另一份含完整规则的YAML内，但是内容超出 65536 了 无法发布。

![Image](https://github.com/user-attachments/assets/09be6af5-3e2d-4cab-ad04-56bf2d80e9a5)

![Image](https://github.com/user-attachments/assets/6e1f3f72-48ab-4296-90e5-17802cec6d9f)
