### ISSUE TITLE
能否直接给输出结果加上规则

### ISSUE THREAD

**Issue by ArronHC** [beck-8/subs-check#21]
为了让手机也能够使用订阅，我将结果传到webDAV，手机访问webDAV中的配置文件，感觉直接给结果加上规则会更方便一些？您怎么看

**Comment by beck-8** [comment]
使用最新版，访问 http://127.0.0.1:8299/api/file/mihomo
得到的就是带规则的订阅
看一下最新版的更新日志

**Comment by beck-8** [comment]
127.0.0.1 改成相应的IP

**Comment by ArronHC** [comment]
感谢回答，我的意思是，能否给程序生成的all.yaml加上规则，不用端口访问，这样上传带规则的配置文件到webdav更方便我手机使用代理

**Comment by ArronHC** [comment]
我现在的解决方案是通过curl把带规则的文件下载到本地，再通过rclone上传到webdav，感觉还是不方便

**Comment by ArronHC** [comment]
> 你运行的机器是在哪里，你的webdav是在哪里呢？
> 
> 生成的all.yaml带规则，目前不会考虑

本地的机器，云上的webdav
好吧，那我只能自己编脚本了😂
另外您有什么好方法能够让手机也用上这个订阅吗？（没有内网环境）

**Comment by beck-8** [comment]
如果是我的话，我会直接访问程序去请求带规则的接口。
然后你可能没有公网，你可以用内网穿透frp也可以访问：iphone -> 云服务 -> 家里的台式机

**Comment by ArronHC** [comment]
> 如果是我的话，我会直接访问程序去请求带规则的接口。
> 然后你可能没有公网，你可以用内网穿透frp也可以访问：iphone -> 云服务 -> 家里的台式机
> 

感谢佬友提供思路❤️～

**Comment by beck-8** [comment]
你的建议我也保留，调研一下（实现不难，得想个完美的方法）

**Comment by beck-8** [comment]
另外，这里假设什么都不做，你上传到webdav的不带规则的文件，你可以经过订阅转换后端加上规则啊，不也能用的吗？这里为啥会折腾这么多道？

**Comment by beck-8** [comment]
生成的配置里，是否需要这些基础信息？ @ArronHC 
```
mixed-port: 7890
allow-lan: false
bind-address: "*"
mode: rule
log-level: info
external-controller: ""
dns:
  enable: true
  ipv6: false
  default-nameserver:
    - tls://223.5.5.5
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  use-hosts: false
  nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  fake-ip-filter:
    - "*"
    - +.lan
    - +.local
    - time.*.com
    - ntp.*.com
    - +.market.xiaomi.com
  use-system-hosts: false
  direct-nameserver: []
  respect-rules: false
```
