### ISSUE TITLE
[BUG]  reality的节点，上游short-id不规范，生成的mihomo.yaml在Flclash中报错“invalid short-id”

### ISSUE THREAD

**Issue by EvelyniceFox** [beck-8/subs-check#81]
### 前置确认

- [x] 我已阅读 [README.md](https://github.com/beck-8/subs-check/blob/master/README.md)，确认问题不是配置错误。
- [x] 我已在 [Issues](https://github.com/beck-8/subs-check/issues) 中搜索，未找到类似的问题。
- [x] 我已在 [config.example.yaml](https://github.com/beck-8/subs-check/blob/master/config/config.example.yaml) 中看过，未找到相关配置

### 问题描述

 > - `client-fingerprint:` chrome
>     flow: xtls-rprx-vision
>     http-opts:
>       headers: {}
>       path:
>         - /
>     name: "\U0001F1FA\U0001F1F8美国44 | ⬇️ 381KB/s|0%|Netflix|Disney|Openai"
>     network: tcp
>     port: 50165
>     reality-opts:
>       public-key: 0IZdGxnmcXWImMAXbuHkLEpykUKzFLYwYaZEMYKZigk
>       short-id: 0f1f0904b469
>     server: 172.82.67.36
>     tls: true
>     type: vless
>     udp: true
>     uuid: dae4313d-1181-4cf4-91bc-2a9d2b91181f
>     xudp: true
>     servername: yahoo.com

上面的节点似乎是正确的格式，有些short-id出错，比如`short-id: 58`, `short-id: 'bjj1212'`, `short-id: ''`，然后Flclash更新后提示“proxy 194: invalid REALITY short ID”，不显示代理节点页面。

### 复现步骤

1、添加了新的订阅，里面有reality节点，但部分节点的short-id格式错误；
2、程序运行完成，没有报错；
3、Flclash提示：“proxy 194: invalid REALITY short ID”
4、不知道是哪条上游订阅里的节点。

### 预期行为

检测不合格的reality 节点，直接剔除。

### 实际行为

在其他客户端中使用时报错。

### subs-check 版本

v2.1.8

### 环境详情

Windows11和安卓

### 日志或截图

无

**Comment by beck-8** [comment]
这可能不符合规范。
晚会我查一下，可能是个BUG

**Comment by beck-8** [comment]
你丢给fclash的是哪个链接？all.yaml mihomo.yaml 还是base64.txt 
看起来应该是你用了base64.txt 格式的丢给了clash ？

**Comment by beck-8** [comment]
你的文件里的配置用代码块包起来

**Comment by beck-8** [comment]
我知道了，是上游不规范，但不是你说的这种不规范
是格式不规范，该缩进的Yaml没有缩进，或者说你给我的信息是错的。
相当于这些字段没有在reality-opts字段里，所以他的检查逻辑也跳过了，然后刚好这个节点不需要reality-opts都可以联通。

**Comment by beck-8** [comment]
在用户补充更多信息前，目前没发现任何问题。

**Comment by mihude** [comment]
我这也遇到了这个提示：proxy 119: invalid REALITY short ID

**Comment by beck-8** [comment]
> 我这也遇到了这个提示：proxy 119: invalid REALITY short ID

提供节点信息，使用代码块括起来。使用方式也讲清楚

**Comment by EvelyniceChen** [comment]
`https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.meta.yml`

来自上面的订阅链接。

比如：
```
- flow: xtls-rprx-vision
  mode: ''
  name: 1|🇺🇸4 |  5.1MB/s
  network: tcp
  port: 29850
  reality-opts:
    public-key: y6tT-wk3_miRmKCQ0G68lR4m6In7ZQ2BAzSzmHBkHhc
    short-id: '19'
  server: 172.82.67.156
  servername: yahoo.com
  tls: true
  type: vless
  udp: false
  uuid: fd25c3d2-01cf-452b-904a-01e57d28cb98
```
